#!/bin/sh
# Retrieve location of this script
SCRIPT_DIR=$( cd -- "$( dirname -- $0 )" &> /dev/null && pwd )
# Run the gradle task quietly
cd $SCRIPT_DIR && ./gradlew run -q --console=plain > tmp.sk
sketch tmp.sk -V 5 --slv-nativeints --bnd-inline-amnt 5
